hydra:
  run:
    dir: ${path:}/env_clf/config/saved_configs/experiments_config/${experiments.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}

defaults:
  - _self_
  - experiments: road_cross  # all | road_cross 

rt_exp: true
save_dir: ../../config/saved_configs/experiments_config/${experiments.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}/
debug: False