## TODO: 
# - add parameters/expirament

project: env_clf
entity: nimrodcurtis
program: env_clf/src/model/train.py
name: sweep_efficientnet  # give name
method: grid
metric:
  goal: maximize
  name: test_accuracy
parameters:
    wandb.run.enable: 
      values: [true]
    model.name:
      values: [EfficientNet]
    model.version:
      values: [efficientnet_b0]
    training.num_epochs:
      values: [15]
    training.save:
      values: [false]
    dataset.train_batch_size:
      values: [24]
    optimizer.learning_rate: 
      values: [0.00005] #  0.00001

command:
  - ${env}
  - python3
  - ${program}
  - ${args_no_hyphens}
