## TODO: 
# - add parameters/expirament

program: env_clf/src/model/train.py
method: grid
metric:
  goal: maximize
  name: test_accuracy
parameters:
    optimizer.learning_rate: 
      values: [0.0001, 0.001]
    

command:
  - ${env}
  - python3
  - ${program}
  - ${args_no_hyphens}
