## TODO: 
# - add parameters/expirament

project: env_clf
entity: nimrodcurtis
program: env_clf/src/model/train.py
name: sweep_resnet  # give name
method: grid
metric:
  goal: maximize
  name: test_accuracy
parameters:
    wandb.run.enable: 
      values: [true]
    model.name:
      values: [ResNet]
    model.version:
      values: [resnet18,resnet34]
    training.num_epochs:
      values: [10,20]
    dataset.train_batch_size:
      values: [16,24,32]
    optimizer.learning_rate: 
      values: [0.0001, 0.00005, 0.00001]

command:
  - ${env}
  - python3
  - ${program}
  - ${args_no_hyphens}
